# Generated by Django 5.0.3 on 2024-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
